version: 1.0.{build}

image: Visual Studio 2022

environment:
  # Встановлюємо версію Python, яку будемо використовувати
  PYTHON_VERSION: "3.9.6"

install:
  # Встановлюємо PyInstaller
  - pip install pyinstaller

build:
  # Запускаємо команду PyInstaller для створення .exe файлу
  script:
    - pyinstaller --onefile --noconsole --icon=icon.ico test22.py

artifacts:
  # Вказуємо шлях до створеного .exe файлу
  - path: dist\test22.exe
    name: test22.exe
